# Generated by Django 2.0 on 2017-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navtabs',
            name='link',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user_avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
