# Generated by Django 2.0 on 2017-12-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171229_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
