# Generated by Django 2.0 on 2017-12-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171231_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(null=True, upload_to='event_pictures'),
        ),
    ]
