# Generated by Django 2.0 on 2017-12-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171231_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=150)),
                ('profiles', models.ManyToManyField(to='blog.Profile')),
            ],
        ),
    ]
