# Generated by Django 2.0 on 2018-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171231_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(related_name='posts', to='blog.Profile'),
        ),
    ]
