# Generated by Django 2.0 on 2018-01-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180102_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quora_link',
            field=models.CharField(default='', max_length=30),
        ),
    ]
