# Generated by Django 2.0 on 2018-01-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180102_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='blogembed',
            options={'verbose_name': 'Embedded File', 'verbose_name_plural': 'Embedded Files'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News Item', 'verbose_name_plural': 'News Items'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
