# Generated by Django 2.0 on 2018-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180102_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
