# Generated by Django 2.0 on 2018-01-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180103_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogembed',
            name='blog',
        ),
    ]
