# Generated by Django 2.0 on 2018-01-05 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_blogembed_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('link', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('new', models.BooleanField(default=True)),
                ('cycle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40)),
                ('priority', models.IntegerField(default=0)),
                ('auto_expire_on', models.DateTimeField(blank=True, null=True)),
                ('start_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='twitter_dps'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.NewsTopic'),
        ),
    ]
